### ISSUE TITLE
Fluxo de Usuário

### ISSUE THREAD

**Issue by graziellyoliveira** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t1-acessibilidade-na-real#24]

**Comment by mflmourao** [comment]
[user flow.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t1-acessibilidade-na-real/files/9735769/user.flow.pdf)
