### ISSUE TITLE
Projeto de Interface - User Flow

### ISSUE THREAD

**Issue by graziellyoliveira** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t1-acessibilidade-na-real#27]
Atualizar no Github a seção "UserFlow" com imagem do diagrama e descrição do mesmo.

**Comment by mflmourao** [comment]
[user flow.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e1-proj-web-t1-acessibilidade-na-real/files/9735810/user.flow.pdf)
